stages:
  - test
  - deploy

  test:
    stage: test
    image: elixir:latest
  
    services:
      - postgres:latest
  
    variables:
      POSTGRES_DB: "webapp_test"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      MIX_ENV: "test"
  
    before_script:
      - apt-get update && apt-get -y install postgresql-client
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix ecto.create
      - mix ecto.migrate
  
    script:
      - mix test
      - mix coveralls
  
  deploy_demo:
    stage: deploy
    image: ubuntu:18.04
    only:
      - master
  
    variables:
      GIGALIXIR_APP_NAME: "welltodo-normal-hen"

    environment:
      name: demo
      url: https://demo.runhyve.app
    
    script:
      - apt-get update && apt-get install -y python-pip git
      - pip install gigalixir
      - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/GIGALIXIR_APP_NAME.git
      - git push -f gigalixir HEAD:refs/heads/master
  
