FROM elixir:1.11
ARG SECRET_KEY_BASE

ENV DEBIAN_FRONTEND=noninteractive
ENV MIX_ENV=prod
ENV SECRET_KEY_BASE=$SECRET_KEY_BASE

RUN mix local.hex --force
RUN mix local.rebar --force

RUN apt-get update && apt-get install -y -q git make inotify-tools curl software-properties-common

RUN mkdir -p /usr/local/runhyve/webapp
ADD . /usr/local/runhyve/webapp
WORKDIR /usr/local/runhyve/webapp
RUN mix deps.get --only-prod
WORKDIR /usr/local/runhyve/webapp
RUN mix compile && mix assets.deploy
