version: '2'

services:
  postgres:
    container_name: postgres
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  webapp:
    container_name: webapp
    depends_on:
    - 'postgres'
    build: .
    ports:
    - 4000:4000
    volumes:
    - '.:/usr/local/runhyve/webapp'
    command: bash -c "mix phx.server"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: 5432
