version: '2'

services:
  postgres:
    container_name: postgres
    image: 'postgres:14.1'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  webapp:
    container_name: webapp
    depends_on:
    - 'postgres'
    build: .
    image: registry.gitlab.com/runhyve/webapp:update
    ports:
    - 4000:4000
    volumes:
    - '.:/usr/local/runhyve/webapp'
    command: bash -c "mix ecto.migrate && mix phx.server"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PORT: 5432
      MIX_ENV: 'dev'
