#!/bin/sh
set -ex

images_dir="$(zfs get -H -o value mountpoint $(iocage get -p))/iocage/images"

run() {
  if [ -f "$images_dir/$1.zip" ]; then
    iocage import $1
    iocage rename $1 $2
    iocage start $2
  else
    echo "No such image"
  fi
}
images() {
  ls -l $images_dir/*.zip
}

build() {
  . tools/lib/jailfile.sh
  . Jailfile
}

command=$1
shift
"$command" "${@}"
